# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: setup node
      uses: actions/setup-node@v2.1.0
      with:
        node-version: '12'
        
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-:  
        
    - name: build
      run: |
        npm install
        npm run build
      
    - name: deploy
      run: |
        git config user.name ixsiid
        git config user.email ixsiid@halzion.net
        git remote set-url origin https://ixsiid:${{ secrets.GITHUB_PASS }}@github.com/ixsiid/www.git
        git fetch
        git checkout master
        git add docs/*
        git commit -m "deploy"
        git push origin master
